const students =
{
    (
        id:1,
        name="Ahmed",
        city="shiben",
    ),
    (
        id:2,
        name:"yasser",
        city:"Tanta",
    ),

    (
        id:3,
        name:"Andera",
        city:"Alexandria",
    )

}
app.get("/student",(req,res)=>
{
    app.get("/student/create",(req,res)=>
{

});
app.get("/student/update",(req,res)=>
{

});
app.get("/student/delete",(req,res)=>
{
});
app.get("/student/:id",(req,res)=>
{

});


app.get("/users",(req,res)=>
{
    res.render("users");
});
})




export  const name = 'Yasser';